# Generated by Django 6.0.4 on 2026-04-19 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='curent_bpd',
            new_name='current_bpd',
        ),
    ]
