# Generated by Django 6.0.4 on 2026-04-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_curent_bpd_country_current_bpd'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.ImageField(default='images/default.jpg', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
